import Head from 'next/head'

import Card from "../components/Card"
import Header from "../components/Header"
import Hero from "../components/Hero"
import Listing from "../components/Listing"
import Footer from "../components/Footer"

var axios = require('axios');

const { jobs } = require("../data/jobs")
export default function Home({ jobsData }) {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/logo.png" />
      </Head> */}
      <Header />
      <div style={{ backgroundColor: "#eeeff7" }}>
        <Hero />
      </div>
      <Listing jobsData={jobsData} />
      <Footer />
    </>
  )
}
export async function getServerSideProps(context) {

  var config = {
    method: 'get',
    maxBodyLength: Infinity,
    url: `http://localhost:8007/api/v1/jobs?limit=10&skip=0`,
    headers: {}
  };

  const allJobs = await axios(config)
  // axios(config)
  //   .then(function (response) {
  //     console.log(JSON.stringify(response.data));
  //   })
  //   .catch(function (error) {
  //     console.log(error);
  //   });

  return {
    props: {
      jobsData: allJobs.data
    }
  }
}