import Head from 'next/head'

import Card from "../components/Card"
import Header from "../components/Header"
import Hero from "../components/Hero"
import Listing from "../components/Listing"

const { jobs } = require("../data/jobs")
export default function Home({ jobsData }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/logo.png" />
      </Head>
      <Header />
      <div style={{ backgroundColor: "#EBEEF3" }}>
        <Hero />
      </div>
      {/* <div style={{
        margin: "auto"
      }}> */}
        <Listing jobsData={jobsData} />
      {/* </div> */}
      {/* <Card /> */}
    </>
  )
}
export async function getServerSideProps(context) {
  return {
    props: {
      jobsData: jobs
    }
  }
}